name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: "./.github/workflows/test.yml"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get target server hostname
        id: get_hostname
        uses: mikefarah/yq@master
        with:
          cmd: yq '.all.hosts.* | key' inventory.yml
      - name: Get target server fingerprint
        id: get_fingerprint
        uses: mikefarah/yq@master
        with:
          cmd: yq '.all.hosts.*.ed25519_fingerprint' inventory.yml
      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ steps.get_hostname.outputs.result }} ssh-ed25519 ${{ steps.get_fingerprint.outputs.result }}
      - run: echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > vault.key
      - run: pip install --upgrade setuptools
      - run: pip install 'ansible ~= 2.9'
      - run: ansible-galaxy collection install -p ./ -r requirements.yml --force
      - run: ansible-playbook ./ansible_collections/ota_bot/deployment/playbooks/deploy.yml


